INSERT INTO newartwork.learn_learn (title, discription, vedio) VALUES
('Horse', 'This dynamic charcoal artwork captures the raw power and grace of a galloping horse. The artist uses strong charcoal strokes to emphasize muscle tone and movement, while soft shading highlights the flowing mane and tail. Symbolizing freedom, strength, and endurance, the piece conveys energy and spirit. Materials include compressed charcoal for deep shadows and vine charcoal for lighter textures, enhanced with blending tools.', 'static/horse.mp4'),

('Adiyogi', 'A spiritual charcoal portrait of Adiyogi, the primordial yogi, radiating calm and infinite wisdom. The detailed facial features, flowing beard, and serene eyes are rendered with delicate charcoal pencils and soft blending. Symbolizing enlightenment, meditation, and inner peace, the artwork evokes devotion and transcendence. The materials used are vine charcoal for soft tonal transitions and compressed charcoal for defining contrasts.', 'static/adiyogi.mp4'),

('Deer', 'This gentle charcoal drawing of a deer portrays innocence, alertness, and natural beauty. The fine texture of the fur and the delicate antlers are created using charcoal pencils and soft blending techniques. The contrast between dark shadows and light highlights emphasizes vulnerability and grace. Symbolically, the deer represents gentleness, intuition, and harmony with nature.', 'static/deer.mp4'),

('Eye', 'A highly detailed charcoal study of a human eye, capturing the complexity and depth of emotion. The intricate iris patterns, reflections, and eyelashes are rendered with precision using fine charcoal pencils and kneaded erasers. The artwork symbolizes perception, awareness, and the window to the soul. Vine charcoal creates subtle shading, while compressed charcoal enhances depth.', 'static/eye.mp4'),

('Monestry', 'This atmospheric charcoal artwork depicts a serene monastery nestled among mountains. Architectural details and natural surroundings are carefully shaded to evoke peace and solitude. The artist uses layering with compressed charcoal and blending tools to capture light filtering through mist. Symbolizing spiritual refuge and contemplation, the piece invites calm reflection.', 'static/monestry.mp4'),

('Newborn_Baby', 'A tender charcoal portrayal of a sleeping newborn baby, emphasizing purity, innocence, and new beginnings. Soft shading with vine charcoal and delicate contouring with charcoal pencils create smooth skin textures and gentle shadows. Highlights are made with erasers to enhance softness. This artwork celebrates the miracle of life and parental love.', 'static/newborn_baby.mp4'),

('Questionmark', 'An abstract charcoal artwork featuring a large question mark, representing curiosity, uncertainty, and the quest for knowledge. The artist uses bold charcoal strokes with high contrast against the white background to create drama and focus. Soft blending in the background adds depth. This piece provokes thought and introspection.', 'static/questionmark.mp4');
