INSERT INTO learn_modals (title, discription, vedio) VALUES
('Baby Leg', 'This minimalist charcoal artwork of a baby’s feet captures the essence of life’s beginnings. The tiny toes and soft curves symbolize innocence, fragility, and warmth. Using vine charcoal for soft shades and charcoal pencils for contouring the feet, the artist conveys tenderness and affection. The contrast of black tones against white space emphasizes simplicity and emotional depth. Kneaded erasers are used to create highlights along the curves, mimicking soft light. This artwork reminds viewers of the beauty in small things and the emotional ties we share with family and beginnings.', 'static/baby_feet.mp4'),

('Eagle', 'An intense charcoal drawing of an eagle, symbolizing freedom, vision, and strength. The piercing eye and sharply detailed beak reflect focus and dominance. Using compressed charcoal for deep blacks and fine pencils for feather textures, the artist captures the spirit of the wild. Highlights are created using precision erasing, especially in the eye and beak areas, giving the eagle a lifelike presence. The background is subtly blended to maintain emphasis on the eagle’s gaze. It’s a portrait of courage and awareness, often associated with leadership and spiritual clarity.', 'static/eagle.mp4'),

('Elephant', 'This majestic charcoal artwork of an elephant emphasizes wisdom, memory, and strength. The textured skin, long trunk, and calm eyes are carefully rendered using layered charcoal strokes and blending tools. Symbolically, elephants represent power with gentleness. Artists used compressed charcoal for volume and vine charcoal for shadows, while detailing was done with charcoal pencils and smudging tools. Highlights on the tusks and ears add dimension. This piece resonates with Indian culture, reflecting the sacred connection of elephants with deities and temples.', 'static/elephant.mp4'),

('Shivaji', 'A bold and respectful tribute to Chhatrapati Shivaji Maharaj, this charcoal portrait captures leadership and valor. The artist has focused on facial features, armor, and turban with strong contrasts using compressed charcoal. Each stroke reflects the bravery and strategic mind of the Maratha king. Symbolically, this artwork stands for resilience, patriotism, and pride. Materials used include various grades of charcoal pencils, fine erasers for ornaments, and textured paper. A powerful artwork to inspire courage and historical reverence.', 'static/shivaji.mp4'),

('Hanuman', 'This powerful depiction of Lord Hanuman in charcoal illustrates divine strength, loyalty, and devotion. His muscular form, expressive eyes, and flowing cloth symbolize immense power grounded in humility. The detailing uses deep compressed charcoal and blending for shadows. The mace, a key symbol of Hanuman, is rendered with precision. This spiritual piece evokes courage and unwavering faith. Materials include vine and compressed charcoal, blending stumps, and highlights done by subtractive erasing techniques. Perfect for devotional settings.', 'static/hanuman_.mp4'),

('Krishna', 'This divine charcoal sketch of Lord Krishna playing the flute captures serenity, love, and spiritual beauty. His face is drawn with smooth lines, subtle shading, and divine aura. The flute, peacock feather, and slight smile are drawn with delicate precision using charcoal pencils. Symbolically, Krishna represents love, mischief, and cosmic order. The background is softened using blending tools. Materials include vine charcoal for soft areas and compressed charcoal for sharper features. This artwork brings peace and joy to its viewers.', 'static/krishna.mp4'),

('Lady', 'This refined charcoal portrait of a woman emphasizes grace, poise, and silent strength. Her facial expression, posture, and hair are rendered using smooth tonal transitions. The artist plays with light and shadow to show depth and emotion. The artwork speaks of beauty, confidence, and dignity. Materials include charcoal pencils for eyelashes and hair strands, compressed charcoal for depth, and erasers for glow effects. It’s a celebration of feminine energy and introspection.', 'static/lady.mp4'),

('Arjun', 'This intense portrait of Arjun from the Mahabharata captures valor, discipline, and surrender to dharma. His gaze is focused, bow ready, and body in perfect composure. Symbolizing the inner warrior and clarity of purpose, this artwork is rendered using sharp charcoal lines, deep shadows, and divine symbols like the crown and bow. Artists use a combination of compressed and vine charcoal, with textured strokes for clothing and armor. This piece connects with anyone seeking motivation and strength through focus.', 'static/arjun.mp4'),

('Old Man', 'A deeply emotional charcoal sketch of an old man, showing wrinkles, sunken eyes, and a lifetime of experiences. The textures of his skin and expression are masterfully captured using fine charcoal pencils and blending. Each wrinkle tells a story of wisdom, loss, and endurance. The monochrome tones enhance the raw emotion. The paper’s grain helps retain smudges and fine strokes. Symbolizing age, resilience, and life’s journey, this artwork is poignant and reflective.', 'static/oldman.mp4'),

('Panchmukhi Hanuman', 'This divine and powerful charcoal artwork depicts Panchmukhi Hanuman with five distinct faces, each symbolizing protection, courage, and spiritual power. Rendered with intricate detailing, the artist uses deep shadows and spiritual symbolism. Each face has unique expression and headgear, drawn with precision using charcoal pencils. The sacred aura around the deity is achieved with smooth blending and highlights. This artwork is intense, protective, and sacred, suitable for spaces of worship and strength.', 'static/panchmukhi.mp4'),

('Rhino', 'A bold depiction of a rhinoceros in charcoal, showcasing raw strength, resilience, and primal beauty. The rugged texture of the rhino’s skin is achieved using layering and deep contrasts. The horn and face are the focal points, drawn with intense detailing. Symbolically, the rhino represents grounded power and perseverance. The artist used compressed charcoal for density and erasers for contour definition. This artwork is ideal for those drawn to the untamed wild.', 'static/rhino.mp4'),

('Brain', 'This conceptual charcoal artwork represents the human brain, its complexity, and mysterious beauty. The grooves, folds, and connections are drawn using precise strokes and shading. The piece symbolizes intelligence, consciousness, and imagination. Artists use fine charcoal for structure and blending for neural textures. The brain’s light and shadow interplay reflects inner thoughts and the balance between logic and emotion. A striking piece for academic or creative spaces.', 'static/brain.mp4'),

('Skull', 'A haunting charcoal silhouette of a ghostly skull, symbolizing mortality, time, and the unknown. The artist uses deep shadows, hollow eyes, and rough textures to create a surreal and chilling atmosphere. Vine charcoal is used for softer fades and compressed charcoal for the dark sockets. Symbolically, it explores human fears and the beauty of transience. This piece invites philosophical reflection and emotional response.', 'static/skull.mp4'),

('Shiv', 'This divine charcoal artwork of Lord Shiva captures calmness, meditation, and transcendence. The third eye, crescent moon, and ash markings are rendered with spiritual intensity. The matted hair and serene face are drawn using dark and soft charcoal for layered effect. The background includes symbolic elements like mountains or snakes, blended into the figure. This artwork is meditative and mystical, perfect for spiritual ambiance.', 'static/shiv.mp4'),

('Stone Chariot', 'A detailed charcoal illustration of the iconic stone chariot at Hampi. The architectural lines, wheels, and carvings are intricately rendered using rulers, charcoal pencils, and erasers. The piece reflects India’s heritage, history, and craftsmanship. Each stone slab and sculpture is shaded with care. The artwork combines realism and reverence, suitable for lovers of culture and travel.', 'static/stonechariot.mp4');
