# Generated by Django 5.2.1 on 2025-08-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artistname',
            field=models.TextField(null='true'),
        ),
    ]
