# Generated by Django 5.2.1 on 2025-08-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_alter_artist_artistname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artistpic',
            field=models.ImageField(default='artists/default.jpg', upload_to='artists/'),
        ),
    ]
