# Generated by Django 5.2.1 on 2025-08-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_alter_artist_artistpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artistpic',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
