# Generated by Django 5.2.1 on 2025-05-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('discription', models.TextField()),
                ('vedio', models.FileField(upload_to='static/')),
            ],
        ),
    ]
