# Generated by Django 5.2.4 on 2025-08-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commision_work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='artist',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
