# Generated by Django 5.2.1 on 2025-08-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commision_work', '0003_alter_commission_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
